improvements and corrections
RelativityMC/VMP-fabric pull request #23
Opened 2022-08-25 20:38 UTC by Aritz331

i changed some things and corrected other things

2022-08-26 06:49 UTC, ishland requested changes
Looks good in general but still have some small issues.

2022-08-26 06:49 UTC, ishland commented on README.md
> +Very Many Players (VMP for short) is a Fabric mod designed to improve general server performance at a high player count
I personally don't think changing this line is a good idea.

2022-08-26 06:49 UTC, ishland commented on README.md
> +_It can also be read [here](/LICENSE)_
Copying license into README seems pretty unnecessary and the original README already have a link to the license.

2022-08-26 06:49 UTC, ishland commented on README.md
> +- Optimizes ticket propagator using MCUtil from PaperMC (patch licensed under MIT)
`the Paper project` is more accurate than `PaperMC` as it also includes Velocity, Waterfall, Starlight and others.

2022-08-26 06:49 UTC, ishland commented on README.md
> +- Optimizes natural spawning with caches and other tricks to reduce the amount of load
```suggestion
- Optimizes natural spawning with caches and other tricks
```

2022-08-28 15:04 UTC, closed without merging

2022-08-28 21:06 UTC, Aritz331 commented
im glad i was useful, i thought i was a piece of 💩