use proper method to hook channel handlers
RelativityMC/VMP-fabric pull request #40
Opened 2023-03-22 13:21 UTC by FlorianMichael

This pull request moves the adding of the packet_priority_handler, in 1.19.4 Mojang added a new method for adding pipeline handlers, this also indirectly fixes the incompatibility with ViaFabricPlus

2023-03-24 10:46 UTC, ishland requested changes
This PR looks good overall but there are some changes needed.

2023-03-24 10:46 UTC, ishland commented on src/main/java/com/ishland/vmp/common/networking/priority/PacketPriorityHandler.java
> +            if (pipeline instanceof SocketChannel) {
This obviously won't work as a `ChannelPipeline` is never going to be a `SocketChannel`

Use `pipeline.channel()` instead.

2023-03-24 10:46 UTC, ishland commented on src/main/java/com/ishland/vmp/common/networking/priority/PacketPriorityHandler.java
> +                final ChannelConfig config = pipeline.channel().config();
Inline this variable.

2023-03-24 18:31 UTC, FlorianMichael commented on src/main/java/com/ishland/vmp/common/networking/priority/PacketPriorityHandler.java
> +            if (pipeline instanceof SocketChannel) {
done, sorry, forgot to change it

2023-03-24 18:31 UTC, FlorianMichael commented on src/main/java/com/ishland/vmp/common/networking/priority/PacketPriorityHandler.java
> +                final ChannelConfig config = pipeline.channel().config();
done

2023-04-12 15:38 UTC, FlorianMichael commented
So is the PR fine now?

2023-04-12 18:04 UTC, toinouH commented
Most probably but ishland is almost never available during the week.
So you might hear more about it on Friday or Saturday.

2023-04-15 03:52 UTC, ishland approved these changes

2023-04-15 06:20 UTC, merged